runtime: python310

handlers:
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
  MYSQL_HOST: "130.61.124.252"
  MYSQL_USER: "developer"
  MYSQL_PASSWORD: "Test123!"
  MYSQL_DB: "chat_app"